version: "2"
services:
  db:
    build: ./db
    image: smaccoun/dara-db
    expose:
        - "5432"
  api:
      build: ./api
      image: smaccoun/dara-api
      ports:
        - "8080:8080"
      environment:
        - SERVANT_ENV=Production
      tty: true
      stdin_open: true
      volumes:
        - ./api:/home/dev/backend
        - ./.local:/root/.local
      links:
          - db